name: UnityGenv2
version: 1.0
main: io.chazza.unitygen.Main
author: Chazmondo
description: #1 Quality & Unique Item-Generator plugin!

commands:
   unitygen:
     description: Main Comand
     aliases: [gen, gens]
     
permissions:
   unitygen.reload:
     default: op
   unitygen.version:
     default: op
   unitygen.give:
     default: op
   unitygen.giveall:
     default: op
   unitygen.help:
     default: op
   unitygen.list:
     default: op
   unitygen.limit.bypass:
     default: op
     
     
     